apiVersion: website.wolcn.net/v1alpha1
kind: Website
metadata:
  labels:
    app.kubernetes.io/name: website-operator
    app.kubernetes.io/managed-by: kustomize
  name: blechnum
spec:
   # TODO(user): Add fields here
   gitRepo: "https://github.com/wolcn/blechnum.git"
   replicas: 2
